# In the following requests the variables baseUrl, user and password are used.
# Their values are set here.
@baseUrl = http://localhost:4004
@user = adminuser
@password = abcd1234



### ------------------------------------------------------------------------
# Read the ID of a book with or without stock
# @name getBookWithoutStock
GET {{baseUrl}}/admin/Books?$filter=stock gt 0&$top=1&$select=ID
Authorization: Basic {{user}}:{{password}}



### Assign the received ID to the variable ID
@ID = {{getBookWithoutStock.response.body.$.value[0].ID}}



### ------------------------------------------------------------------------
# Retrieve the ETag belonging to the read book
# @name getETag
GET {{baseUrl}}/admin/Books({{ID}})
Authorization: Basic {{user}}:{{password}}



### Assign the received ETag to the variable ETag
@ETag = {{getETag.response.headers.ETag}}



### ------------------------------------------------------------------------
# Delete the corresponding book using the ID and the ETag retrieved above
DELETE {{baseUrl}}/admin/Books({{ID}})
If-Match: {{ETag}}
Authorization: Basic {{user}}:{{password}}