# In the following requests the variable baseUrl is used.
# Its value is set here.
@baseUrl = http://localhost:4004




### ------------------------------------------------------------------------
# Create a new author
# ... and assign the ID of the newly created author to the variable authorID
# @name createNewAuthor
POST {{baseUrl}}/admin/Authors
Content-Type: application/json

{
  "name": "Initial Version"
}

###
@authorID = {{createNewAuthor.response.body.$.ID}}



### Read the newly created author for editing a first time
# ... and assign the received ETag to the variable ETag1
GET {{baseUrl}}/admin/Authors({{authorID}})

###
@ETag1 = {{createNewAuthor.response.headers.ETag}}



### Read the newly created author for editing a second time
# ... and assign the received ETag to the variable ETag2
GET {{baseUrl}}/admin/Authors({{authorID}})

###
@ETag2 = {{createNewAuthor.response.headers.ETag}}



#   ETag1 and Etag2 match because no changes have been made yet.



### ------------------------------------------------------------------------
# Update the newly created author using ETag1 received 
# when the Author was first read.
# The update implicitly creates a new ETag value.
PUT {{baseUrl}}/admin/Authors({{authorID}})
If-Match: {{ETag1}}
Content-Type: application/json

{
  "name": "Update 1 of Initial Version"
}



### ------------------------------------------------------------------------
# Try another update using ETag2 received
# when the author was read for the second time.
# This will fail with a HTTP status code 412 Precondition Failed.
PUT {{baseUrl}}/admin/Authors({{authorID}})
If-Match: {{ETag2}}
Content-Type: application/json

{
  "name": "Update 2 of Initial Version"
}
