# In the following requests the variable baseUrl is used.
# Its value is set here.
@baseUrl = http://localhost:4004


### ------------------------------------------------------------------------
# Get Service Document
GET {{baseUrl}}/admin


### ------------------------------------------------------------------------
# Get Service Metadata Document
GET {{baseUrl}}/admin/$metadata


### ------------------------------------------------------------------------
# Get all books
GET {{baseUrl}}/admin/Books


### ------------------------------------------------------------------------
# Get all authors
GET {{baseUrl}}/admin/Authors


### ------------------------------------------------------------------------
# Create a new author, then update it and finally delete it again
# @name createNewAuthor
POST {{baseUrl}}/admin/Authors
Content-Type: application/json

{
  "name": "Friedrich Schiller",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1805-05-09"
}

###

@authorID = {{createNewAuthor.response.body.$.ID}}

PATCH  {{baseUrl}}/admin/Authors({{authorID}})
Content-Type: application/json

{
  "name": "Johann Christoph Friedrich Schiller"
}

###

DELETE {{baseUrl}}/admin/Authors({{authorID}})